// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
 
#include "NativeGameplayTags.h"

namespace MageAndSeekerGameplayTag
{
	/* Input Tag */
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interection);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Artifact)

	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BookChange_Fire);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BookChange_Ice);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_BookChange_Lightning);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ManaRecharge);

	/*Mage Tag*/
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Status_Book_Fire);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Status_Book_Ice);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Status_Book_Lightning);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Status_CombatMode);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Status_ManaRecharging);

	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Ability_BookChange);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Ability_Attack);

	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Event_ActivateBookChangeEffect);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Event_SpawnProjectile);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Event_ModeChange);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Event_APCharge);

	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Data_ManaChargePer);
	MAGEANDSEEKER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mage_Data_APChargePer);
}